---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # dependsOn:
  #   - name: kube-prometheus-stack-crds
