apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SnUiLnkxP1jtT7yWMuV2pkz4lK6WrgZBkwNvePBjEs7BOHPCxkCdeA==,iv:r3Lk4EwaG0xr4JxYrT8mhXo6IkTc839UB1uE4LZkVwc=,tag:3vE04RZpz9MHcltnwkzVwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j755c5lsqrgr3xq4k53t2gd40tqk8ngwf3kl23tgptk2zqj3fgcss9xqjl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NzN1VUNCOEtsZEYyUUs5
            TlUwYnkzcVBoQmlaWDlzcFpic1RVQ3dDd0hBClpTTzdPVnJqNkhyNkFLWGNyOWdC
            Z25OZHFMUmN2RW9VLzVuUWhpTUVPRjAKLS0tIGZQb3ZxcGFIZ2R6S3hIeDdNTjZ6
            VUNBc3BhbW1jdmxlSHd6WXlLL1crWWsKLolkK6S239QGjB+1MJiQVRaNbF60Y9v9
            IvAyGBsWo0S6tl1k9SOD7t7/4NzyD1uugyu3+efQUgVHfEZxPuW+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T17:07:43Z"
    mac: ENC[AES256_GCM,data:geFNHqQEClKJL+zT8/u6rp3a2QrUcPDbgy2ABrZ0O8cnGxkWfKJL9ySJZ05EIdPdOYb0eVu8w2u3I3XoFQMNEXYJ9gGCUOX+MhnQAHOtsYvoRaRM0EL4P4GIRqI5R1REuvUmbkvkSD+M7a5g0ukbDmxAMM9Gr+H0CBz/opyfal8=,iv:RsDH1kFJ4eBIYpu6r0El57G7n+7h6Ur4j1qzhpERdZc=,tag:6MY8L4i+iEEwfdewoLCesA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
