---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: demo-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: accessKeyId
    remoteRef:
      # 1password-entry-name
      key: "Demo Credentials"
      # 1password-field
      property: accessKeyId
  - secretKey: secretKey
    remoteRef:
      # 1password-entry-name
      key: "Demo Credentials"
      # 1password-field
      property: secretKey
