---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    connect:
      serviceType: ClusterIP
      credentialsName: onepassword-connect-secret
