apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AUiyN3LtVYL218NGxak=,iv:HJMAJ+NZ6LPTDDnvAdRTQMJ7iqzXiWt2XV2wIhoJ08c=,tag:bGsbkVoEmKj3iDQwAvoshA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/87DzADm0cD1vbVByLi21/Xl,iv:JUVqIxjm8XkwGHcBkETBbcUBLYO798pOwP2NxYljCmE=,tag:We5CmpndZkN1wFNf9ldi2g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3Gw1etjJkYsj7oqxRsvqf6ikpmr+MiaC5cAfW1QT44YHQIyp,iv:UmzVINSGaYru0R3OBdeeZU7NrayDIjv7VYuuj6XFuCU=,tag:ExDrtrVLCsOmG8Z6bGgGlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j755c5lsqrgr3xq4k53t2gd40tqk8ngwf3kl23tgptk2zqj3fgcss9xqjl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnZZcjQ3UHhNNXNmenFs
            eE1PR0k0NEhzSmtYalNhZG5Tcm1DRE5JSzB3Cll3U2c4bGxXdk1laFVLRjl0d2JP
            bDZjd2wrNkl0UytUbHdmN0czYXRKVjgKLS0tIDJPazNhY3hjSFh3OHN3RUZSN21w
            M09KVHFQUXc5L3Myamc3Z1dURGtQY2MKOlUOkU2/abYo8qFmNvRq8BjfFK1vRhdV
            Y7uosXZVQ9NlhApSypPdP3SUM/HE2czK3gzXr5vUflUcoOj81Yn8kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T11:31:49Z"
    mac: ENC[AES256_GCM,data:11myPCqH4El0gAVlD6jKLLEv7vdqIWK8BZlUzkvkO7Tjta0SsxnQ9MiYpLGCCTy4lkic8lsreHIGQgMMPKRZJ949TzYRNRf5D7jtG44YGZB8myNKodsKkhIRfX2yPZEPAEQAWOZtYxhPS33PuqsEc2w76qvfVM2g7wQ295+Cqqk=,iv:sftDCJudCbmuagsN289eKxOlWnKH6gWt8wDCPjL3DIs=,tag:CaWdGgdwgvbxzL1UPVLcYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
