---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
            - host: "{{ .host }}"
              port: 5000
              https: false
              username: "{{ .username }}"
              password: "{{ .password }}"
  data:
    - secretKey: host
      remoteRef:
        key: "Synology CSI Login" # 1password-entry-name
        property: host            # 1password-field
    - secretKey: username
      remoteRef:
        key: "Synology CSI Login"
        property: username
    - secretKey: password
      remoteRef:
        key: "Synology CSI Login"
        property: password
